# FROM is the found expected Python version
FROM python:2.7
# Set the working directory to /app
WORKDIR /app
# Add install commands for all of the python modules
RUN ["pip","install","--upgrade","pip"]
# Copy the specified directory to /app
COPY snippet.py /app
# Run the specified python file
CMD ["python", "/app/snippet.py"]