# FROM is the found expected Python version
FROM python:2.7
# Set the working directory to /app
WORKDIR /app
# Add install commands for all of the python modules
RUN ["pip","install","--upgrade","pip"]
RUN ["pip","install","--trusted-host","pypi.python.org","--default-timeout=100","tensorflow==2.1.0"]
RUN ["pip","install","--trusted-host","pypi.python.org","--default-timeout=100","image==1.5.27"]
RUN ["pip","install","--trusted-host","pypi.python.org","--default-timeout=100","util==0.0.1"]
RUN ["pip","install","--trusted-host","pypi.python.org","--default-timeout=100","pillow==10.3.0"]
# Copy the specified directory to /app
COPY snippet.py /app
# Run the specified python file
CMD ["python", "/app/snippet.py"]